#!/bin/bash
#SNAP: https://www.terminal.com/snapshot/f2f554a3d2c7a899be901334ec6926c9d1a062ada1b7c3fdc31622d43649fec8
# Script to deploy FatFree CRM at Terminal.com

INSTALL_PATH="/root"

# Includes
wget https://raw.githubusercontent.com/terminalcloud/apps/master/terlib.sh
source terlib.sh || (echo "cannot get the includes"; exit -1)

install(){
	# Basics
	pkg_update
	system_cleanup
	basics_install

	# Procedure: 
	ruby_install
	cd $INSTALL_PATH
	echo "source /usr/local/rvm/scripts/rvm" >> .bashrc
	git clone https://github.com/fatfreecrm/fat_free_crm.git
	# You should have the database file modified
	cp fat_free_crm/config/database.mysql.yml fat_free_crm/config/database.yml
	mysql_install
	apt-get -y install build-essential libmysqlclient-dev
	gem install mysql2
	gem install activerecord-mysql2-adapter
	apt-get -y install libmagick++-dev libxml2 libxml2-dev libxslt1.1 libxslt1-dev libpq-dev # libyaml-de
	cd fat_free_crm
	gem install nokogiri -v '1.6.5'
	sed -i 's/pg/mysql2/g' Gemfile
	sed -i 's/password\:/password\:\ root/g' ./config/database.yml
	bundle install
    rake db:create
	rake db:migrate
	rake ffcrm:setup:admin USERNAME=admin PASSWORD=t3rminal EMAIL=admin@example.com
	rake ffcrm:demo:load # Only for Demo version
	rails server &
}

install_hooks(){
    mkdir -p /CL/hooks/
    cat > /CL/hooks/startup.sh << ENDOFFILE

#!/bin/bash

name="fatfree"

export PATH=\$PATH:/srv/cloudlabs/scripts


# Getting the doc and styles
wget -q -N --timeout=2 https://raw.githubusercontent.com/terminalcloud/apps/master/docs/"\$name".md
wget -q -N --timeout=2 https://raw.githubusercontent.com/terminalcloud/apps/master/docs/termlib.css && mv termlib.css /root/


# Making the file...
cat > /root/info.html << EOF
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="termlib.css" />
<p id="exlink"><a id="exlink" target="_blank" href="http://\$(hostname)-3000.terminal.com"><b>Test your installation here!</b></a></p>
</head>
<body>
EOF

# Converting markdown file
markdown "\$name.md" >> /root/info.html

# Closing file
cat >> /root/info.html << EOF
</body>
</html>
EOF

# Convert links to external links
sed -i 's/a\ href/a\ target\=\"\_blank\"\ href/g' /root/info.html

# Update server URL in Docs
sed -i "s/terminalservername/\$(hostname)/g" /root/info.html


# Showing up
cat | /srv/cloudlabs/scripts/run_in_term.js	 << EOF
/srv/cloudlabs/scripts/display.sh /root/info.html
EOF

ENDOFFILE

chmod 777 /CL/hooks/startup.sh
}

install && install_hooks

#RUN: echo "installation complete"
